# Generated by Django 6.0.7 on 2026-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationlog',
            name='beverage_type',
            field=models.CharField(choices=[('water', 'Water'), ('sports', 'Electrolytes'), ('caffeine', 'Coffee/Soda'), ('alcohol', 'Alcohol')], default='water', max_length=15),
        ),
        migrations.AddField(
            model_name='hydrationlog',
            name='modifier',
            field=models.FloatField(default=1.0),
        ),
    ]
