# Generated by Django 6.0.7 on 2026-07-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_hydrationlog_net_amount_userprofile_streak_rescues_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydrationlog',
            old_name='net_amount',
            new_name='net_hydration',
        ),
    ]
