# Generated by Django 6.0.7 on 2026-07-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_rename_net_amount_hydrationlog_net_hydration'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='vibe',
            field=models.CharField(choices=[('friendly', 'Friendly drop (💧)'), ('urgent', 'Urgent alert (🚨)'), ('challenge', 'Playful challenge (🏆)')], default='friendly', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_volume_label',
            field=models.CharField(default='Travel Flask', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='custom_volume',
            field=models.FloatField(default=0.3),
        ),
    ]
